config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'static_pages/contact'

  get 'static_pages/about'

  resources :clubs

end

app/models/club.rb
class Club < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

before_action :find_club, only:[:edit, :show]

  def index
		@clubs = Club.all
  end

  def new
		@club = Club.new
  end

  def edit
  end

  def show
  end

private

  def find_club
    @club = Club.find(params[:id])
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def new
  end

  def edit
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clubs/edit.html.erb
<h1>Clubs#edit</h1>
<p>Find me in app/views/clubs/edit.html.erb</p>

app/views/clubs/index.html.erb
<h1>Clubs#index</h1>
<p>Find me in app/views/clubs/index.html.erb</p>

app/views/clubs/new.html.erb
<h1>Clubs#new</h1>
<p>Find me in app/views/clubs/new.html.erb</p>

app/views/clubs/show.html.erb
<h1>Clubs#show</h1>
<p>Find me in app/views/clubs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slcnights</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<a><%= link_to 'Home', root_path %></a>
<a><%= link_to 'About Me', static_pages_about_path %></a>
<a><%= link_to 'Clubs', clubs_path %></a>
<a><%= link_to 'Contact', static_pages_contact_path %></a>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Me</h1>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/static_pages/home.html.erb
<h1>SLC Nights</h1>

<h3>Everything you need to know about Salt Lake City's nightclub scene</h3>